# Generated by Django 3.0.5 on 2020-05-26 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebrowser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='game',
        ),
        migrations.AddField(
            model_name='log',
            name='game_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('W', 'Want to play'), ('C', 'Currently playing'), ('F', 'Finished Playing'), ('D', 'Dropped'), ('H', 'Hundred Complete'), ('O', 'On hold')], default='W', max_length=6),
        ),
        migrations.AlterField(
            model_name='log',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
